### ISSUE TITLE
zencoder chat error.

### ISSUE THREAD

**Issue by danilovmy** [forgoodaigithub/zencoder-vscode-plugin#3] opened 2024-09-20 14:21 UTC
Vscode. After plugin install, choose command "Zencoder openchat".
Getting an error:
```
{
    "type": "Error",
    "value": "Chat ID is not provided",
    "stacktrace": { ... }
}
```

**Comment by iurii-iufimov-forgood** [comment] 2024-09-26 19:15
@danilovmy , thanks for the report!
The issue is fixed in version `0.0.10`

**Closed by iurii-iufimov-forgood** 2024-09-26 19:15 UTC
